### ISSUE TITLE
Get This Error After Update

### ISSUE THREAD

**Issue by Pawansingh333** [jawikas/hamsterkombat#2]
—— Enter the new combo items (3 items):
   —— Enter item 1: Villa_for_DEV_team
   —— Enter item 2: YouTube_25_million
   —— Enter item 3: Quaterfinals_are_coming
Traceback (most recent call last):
  File "C:\Users\abc\Desktop\pixelversexyzbot-main\hamsterkombat-main\hamsterkombat-main\main.py", line 12, in <module>
    main()
  File "C:\Users\abc\Desktop\pixelversexyzbot-main\hamsterkombat-main\hamsterkombat-main\src\core.py", line 196, in main
    set_combo()
  File "C:\Users\abc\Desktop\pixelversexyzbot-main\hamsterkombat-main\hamsterkombat-main\src\core.py", line 162, in set_combo
    for filename in os.listdir(logs_folder):
                    ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'logs'

C:\Users\abc\Desktop\pixelversexyzbot-main\hamsterkombat-main\hamsterkombat-main>

**Comment by jawikas** [comment]
if anyone is experiencing this problem then do Add folder on main root project with name "logs" and run the bot again.
![image](https://github.com/jawikas/hamsterkombat/assets/63976518/7b80105c-eb47-4c06-ac9c-1b9697bcddaf)
